### ISSUE TITLE
Changes in 96cfda79 causing segmenation fault with TensorFlow Lite unit tests

### ISSUE THREAD

**Issue by robert-kalmar** [VeriSilicon/tflite-vx-delegate#119]
The changes introduced in rev 96cfda79f64989bb627cc8aead40b76a5badc65e cause Segmentation Fault with TensorFlow Lite unit tests. The fixes in 0598ab9dbfea1af23bb254acc2bb4b7f272e7790 and 9a80eaf4376e8880066c422cc6c61a629db44316 does not resolve the problem. 
Platform i.MX8MP
```
$ ./activations_test --external_delegate_path=/test_files/usr/lib/libvx_delegate.so 
[==========] Running 134 tests from 9 test suites.
[----------] Global test environment set-up.
[----------] 8 tests from FloatActivationsOpTest
[ RUN      ] FloatActivationsOpTest.Elu
EXTERNAL delegate created.
Segmentation fault
```

**Comment by sunshinemyson** [comment]
@chenfeiyue-cfy , Could you comment?

**Comment by chenfeiyue-cfy** [comment]
It didn't appear in 2bf0469 or eaf4c96.

**Comment by sunshinemyson** [comment]
@robert-kalmar @chenfeiyue-cfy ,

We figured out other issue in https://github.com/VeriSilicon/tflite-vx-delegate/commit/96cfda79f64989bb627cc8aead40b76a5badc65e. It can solve this problem, we will update patch in this week.

**Comment by sunshinemyson** [comment]
Fixed
