### ISSUE TITLE
Does anyone who run the test_convX case all passed?

### ISSUE THREAD

**Issue by Genlk** [VeriSilicon/tflite-vx-delegate#135]
I've run the conv2D and conv3D test.
The result shows that some cases faild!

In the conv2D ,6failed 2passed 
![image](https://user-images.githubusercontent.com/24912927/186621841-b0664ad9-4af1-4b07-b57e-c8a581605483.png)

In the conv3D ,40failed,0passed
![image](https://user-images.githubusercontent.com/24912927/186621626-e6c95814-be34-4c39-b73a-f3ce33b1dde2.png)

**Comment by sunshinemyson** [comment]
@Genlk ,

For conv3D, yes, it still not work. But for Conv2D it can pass from our in-house test. Could you share more information about the software configuration in your test?

Thanks

**Comment by Genlk** [comment]
> @Genlk ,
> 
> For conv3D, yes, it still not work. But for Conv2D it can pass from our in-house test. Could you share more information about the software configuration in your test?
> 
> Thanks


“For conv3D, yes, it still not work. ” 
                               ------You means that the pytest is not work, or the tim-vx(tflite-vx-delegate) doesn't suport the Conv3d?

For the conv2D,I have modify the tolerance to 1e-3(default 1e-6) in the last line of test script, it works!

**Comment by Genlk** [comment]
> > @Genlk ,
> > For conv3D, yes, it still not work. But for Conv2D it can pass from our in-house test. Could you share more information about the software configuration in your test?
> > Thanks
> 
> “For conv3D, yes, it still not work. ” ------You means that the pytest is not work, or the tim-vx(tflite-vx-delegate) doesn't suport the Conv3d?
> 
> For the conv2D,I have modify the tolerance to 1e-3(default 1e-6) in the last line of test script, it works!

@sunshinemyson

**Comment by Genlk** [comment]
@sunshinemyson 
I've saw the release log,you added the feature "Added Conv3D API inside lowlevel driver without dilation support." in version V1.1.37.
What does it mean "inside lowlevel driver",I have not see the limit  in other ops feature
![image](https://user-images.githubusercontent.com/24912927/187614578-bd722b41-4ca7-4713-ad57-48ec729b92c9.png)

Is that means the conv3d is not totally support?

**Comment by sunshinemyson** [comment]
> @sunshinemyson I've saw the release log,you added the feature "Added Conv3D API inside lowlevel driver without dilation support." in version V1.1.37. What does it mean "inside lowlevel driver",I have not see the limit in other ops feature ![image](https://user-images.githubusercontent.com/24912927/187614578-bd722b41-4ca7-4713-ad57-48ec729b92c9.png)
> 
> Is that means the conv3d is not totally support?

@Genlk ,

we support conv3d but with some restriction, the team will update mapping then you will know the restrictions. And we will make sure conv3d can pass with kernel test.

Thanks

**Comment by chxin66** [comment]
> > > @Genlk ,
> > > For conv3D, yes, it still not work. But for Conv2D it can pass from our in-house test. Could you share more information about the software configuration in your test?
> > > Thanks
> > 
> > 
> > “For conv3D, yes, it still not work. ” ------You means that the pytest is not work, or the tim-vx(tflite-vx-delegate) doesn't suport the Conv3d?
> > For the conv2D,I have modify the tolerance to 1e-3(default 1e-6) in the last line of test script, it works!
> 
> @sunshinemyson
we have fixed conv3d kernel test in vx_delegate just now
