### ISSUE TITLE
Missing bias tensor is not handled correctly in FullyConnected 

### ISSUE THREAD

**Issue by robert-kalmar** [VeriSilicon/tflite-vx-delegate#60]
The bias tensor at FullyConnected layer is optional. The implementation https://github.com/VeriSilicon/tflite-vx-delegate/blob/debeff61ebbf1366534878ded23990261600922b/op_map.cc#L447 does not handles this correctly. The bias tensor (index 2 in `node->inputs->data[]` ) can be -1, which indicates the bias tensor is missing. 
```
    for (int i = 0; i < node->inputs->size; i++) {
      int input_index = node->inputs->data[i];
      if (context->tensors[input_index].type == kTfLiteInt16) {
        TFLITE_LOG_PROD(TFLITE_LOG_ERROR, "Int16 input is not supported");
        return false;
      }
    }
```
If the bias tensor is missing the VX Delegate crash with Segmentation Fault (tries to access invalid index: `context->tensors[-1].type` )

**Comment by sunshinemyson** [comment]
@robert-kalmar ,

Yes, we are going to fix this soon. Thanks for point out the issue. Beside this issue, we also need Tim-vx's change to support FullConnected with input/weight only.
