### ISSUE TITLE
gather_nd_test results are non-deterministic

### ISSUE THREAD

**Issue by robert-kalmar** [VeriSilicon/tflite-vx-delegate#66]
The results of the gather_nd_test from TensorFlow Lite Unit tests are nondeterministic. When the unit test binary is executed multiple times, the list of failed tests is different: 
```
$ ./gather_nd_test --external_delegate_path=/usr/lib/libvx_delegate.so
...
[----------] Global test environment tear-down
[==========] 26 tests from 1 test suite ran. (1100 ms total)
[  PASSED  ] 15 tests.
[  FAILED  ] 11 tests, listed below:
[  FAILED  ] GatherNdOpTest.ElementIndexingIntoMatrix
[  FAILED  ] GatherNdOpTest.SliceIndexingIntoMatrix
[  FAILED  ] GatherNdOpTest.BatchedIndexingIntoMatrix1
[  FAILED  ] GatherNdOpTest.SliceIndexingIntoRank3Tensor
[  FAILED  ] GatherNdOpTest.BatchedIndexingIntoRank3Tensor1
[  FAILED  ] GatherNdOpTest.BatchedIndexingIntoRank3Tensor4
[  FAILED  ] GatherNdOpTest.DuplicateIndexingIntoRank3Tensor
[  FAILED  ] GatherNdOpTest.Float32Int32
[  FAILED  ] GatherNdOpTest.Int32Int32
[  FAILED  ] GatherNdOpTest.Uint8Int32
[  FAILED  ] GatherNdOpTest.Int8Int32

11 FAILED TESTS
```
```
$ ./gather_nd_test --external_delegate_path=/usr/lib/libvx_delegate.so
...
[----------] Global test environment tear-down
[==========] 26 tests from 1 test suite ran. (1102 ms total)
[  PASSED  ] 13 tests.
[  FAILED  ] 13 tests, listed below:
[  FAILED  ] GatherNdOpTest.SliceIndexingIntoMatrix
[  FAILED  ] GatherNdOpTest.BatchedIndexingIntoMatrix1
[  FAILED  ] GatherNdOpTest.BatchedIndexingIntoMatrix2
[  FAILED  ] GatherNdOpTest.ElementIndexingIntoRank3Tensor
[  FAILED  ] GatherNdOpTest.SliceIndexingIntoRank3Tensor
[  FAILED  ] GatherNdOpTest.BatchedIndexingIntoRank3Tensor1
[  FAILED  ] GatherNdOpTest.BatchedIndexingIntoRank3Tensor2
[  FAILED  ] GatherNdOpTest.BatchedIndexingIntoRank3Tensor4
[  FAILED  ] GatherNdOpTest.DuplicateIndexingIntoRank3Tensor
[  FAILED  ] GatherNdOpTest.Float32Int32
[  FAILED  ] GatherNdOpTest.Int32Int32
[  FAILED  ] GatherNdOpTest.Uint8Int32
[  FAILED  ] GatherNdOpTest.Int8Int32

13 FAILED TESTS
```

**Comment by sunshinemyson** [comment]
@robert-kalmar ,

Thanks for sharing. We will check it.

**Comment by chxin66** [comment]
Please use our latest timvx code and you won't have this problem

**Comment by robert-kalmar** [comment]
@sunshinemyson , 
I don't see too much difference btw 2.9.1 and 2.7.0 (original finding). Can you replicate those issues (and the non-determinicity) on your side?

**Comment by chxin66** [comment]
I checkout to VX Delegate: Revision e04ebf7 & TIM-VX 3e8d5e3493cc8bbd6908b72d2b7fe2d508a397c4 + "Supoort layout inference for PRule" & tensorflow 2.9.1, the gather_nd_test are all pass.，Please check again if the environment is correct
![企业微信截图_16577894099516](https://user-images.githubusercontent.com/57057788/178945723-3de365d4-72a7-4193-97e4-6d93c90dfa0c.png)
![企业微信截图_16577894254706](https://user-images.githubusercontent.com/57057788/178945733-3ff1f361-3d65-4fc3-896f-aeb45a2f763a.png)

**Comment by sunshinemyson** [comment]
@robert-kalmar ,

I think there different between you and us may raised by different version of OVXLIB. Which version of ovxlib you take in your test?

Thanks

**Comment by robert-kalmar** [comment]
@sunshinemyson , 
I am using the standalone OVXLIB, which shall correspond to patch release _rel_6.4.3.p4_20220609_ from our GPU driver delivery.

**Comment by robert-kalmar** [comment]
@sunshinemyson 
I did another thest with stadalone OVXLIB, corresponding to patch release rel_6.4.3.p4_20220714, problem still exist. 
I can reproduce the problem even with your revisions:
![image](https://user-images.githubusercontent.com/56120470/181519687-d507b78c-48ea-45de-b305-13ff8f04456f.png)
![image](https://user-images.githubusercontent.com/56120470/181519858-d0a26183-b2f4-4e6f-b872-0114faf9aa07.png)

**Comment by sunshinemyson** [comment]
We are not able to reproduce this.
