### ISSUE TITLE
benchmark_model failed with: Create tensor fail!

### ISSUE THREAD

**Issue by tonysung** [VeriSilicon/tflite-vx-delegate#71]
Run TFLite's `benchmark_model` with `libvx_delegate` result in multiple "Create tensor fail!" and segmentation fault.

* Android 9 32bit, Amlogic A311D
* `benchmark_model` built from TensorFlow v2.8.0 and works perfectly with all first-party delegates.
* `tim-vx` built from https://github.com/VeriSilicon/TIM-VX/commit/f2e71a3deb178a862c0907a688d0557d1242c101
* `tflite-delegate` built from https://github.com/VeriSilicon/tflite-vx-delegate/commit/5447c63880f4f044f2721f03ddc7d0214e2aebb7
* SDK: `arm_android9_A311D_6.4.3`

Tried these two models from https://www.tensorflow.org/lite/guide/hosted_models and the results are the same:
* [mobilenet_v1_0.25_128_quant](https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_2018_08_02/mobilenet_v1_0.25_128_quant.tgz)
* [mobilenet_v2_1.0_224_quant](https://storage.googleapis.com/download.tensorflow.org/models/tflite_11_05_08/mobilenet_v2_1.0_224_quant.tgz)

Example output:

```
$ adb shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/benchmark_model --graph=/data/local/tmp/mobilenet_v2_1.0_224_quant.tflite --external_delegate_path=/data/local/tmp/libvx_delegate.so

STARTING!
Duplicate flags: num_threads
Log parameter values verbosely: [0]
Graph: [/data/local/tmp/mobilenet_v2_1.0_224_quant.tflite]
External delegate path: [/data/local/tmp/libvx_delegate.so]
Loaded model /data/local/tmp/mobilenet_v2_1.0_224_quant.tflite
INFO: Initialized TensorFlow Lite runtime.
Vx delegate: allowed_cache_mode set to 0.
Vx delegate: allowed_builtin_code set to 0.
Vx delegate: error_during_init set to 0.
Vx delegate: error_during_prepare set to 0.
Vx delegate: error_during_invoke set to 0.
EXTERNAL delegate created.
INFO: Initialize supported_builtins
INFO: Replacing 65 node(s) with delegate (Vx Delegate) node, yielding 1 partitions.
INFO: vx_delegate Delegate::Init
INFO: Initialize supported_builtins
INFO: Delegate::Prepare node: 0xac9111e0
Explicitly applied EXTERNAL delegate, and the model graph will be completely executed by the delegate.
The input model file size (MB): 3.57776
Initialized session in 33.502ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
INFO: Delegate::Invoke node: 0xac9111e0
E [/ext/tim-vx/src/tim/vx/tensor.cc:Init:221]Create tensor fail!
E [/ext/tim-vx/src/tim/vx/tensor.cc:Init:221]Create tensor fail!
E [/ext/tim-vx/src/tim/vx/tensor.cc:Init:221]Create tensor fail!
E [/ext/tim-vx/src/tim/vx/tensor.cc:Init:221]Create tensor fail!
E [/ext/tim-vx/src/tim/vx/tensor.cc:Init:221]Create tensor fail!
INFO: Creating Conv2d op
Segmentation fault
```

**Comment by sunshinemyson** [comment]
Hi Tonysung,

Please share your dmesg log and Android logcat content. 
I think your driver stack not loaded properly.

Thanks

**Comment by tonysung** [comment]
Here you go:
[dmesg-before-run.txt](https://github.com/VeriSilicon/tflite-vx-delegate/files/8362046/dmesg-before-run.txt)
[dmesg-after-run.txt](https://github.com/VeriSilicon/tflite-vx-delegate/files/8362045/dmesg-after-run.txt)
[logcat-during-run.txt](https://github.com/VeriSilicon/tflite-vx-delegate/files/8362047/logcat-during-run.txt)

Please note that the **Segmentation fault** happens after the **Create tensor fail!** error message.

**Comment by tonysung** [comment]
Are these information sufficient?

**Comment by sunshinemyson** [comment]
@tonysung ,

I checked it internally, your driver out of date, you can try it with the guideline by baidu:
https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/docs/demo_guides/verisilicon_timvx.md

Thanks
