### ISSUE TITLE
Usefull or just for fun!

### ISSUE THREAD

**Issue by 2050airobert** [VeriSilicon/tflite-vx-delegate#92]
hi，
1 I don not know what you said below.
"benchmark_model/Label_image compatible with Tflite+NBG."
2 There is a realworld quesion, if I have a more layers and newest tflite model, could I transfer it by this acuitylite tool to generate the testcase of my tflite mode? Or it supports only few and old cnn models?

3 What is the real use of this tflite-vx-delegate? It will generate the testcase of any tflite model , and we just need run the demo code or projcect  generated by the tool? 
4 Is there any detailed step to intruduce the use of this tool?  If  I use this tool,then I do not need any other like tengine etc,right?
BR

**Comment by chxin66** [comment]
To3: The role of tflite-vx-delegate is to map the tflite model on our npu, and the supported ops will run on our npu. The model can be run through benchmark_model or minimal, and the process of delegating the model to the npu will be performed in invoke().
To4: tflite-vx-delegate/README.md will teach you how to build and run.

**Comment by sunshinemyson** [comment]
@2050airobert ，

As we discussed in https://github.com/VeriSilicon/TIM-VX/issues/412. 
The vx-delegate is our official support for tensorflow-lite runtime - it's production quality and promised long time support. In concept, this repo is not a tool but a backend for tensorflow-lite runtime.
